# Generated by Django 5.2.10 on 2026-01-31 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('property', '0002_alter_agency_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agency this user belongs to. Agency staff can only manage their own properties.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='property.agency'),
        ),
    ]
