# Generated by Django 5.2.10 on 2026-01-28 11:12

import apps.property.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'commune',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'wilaya',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.property.models.agency_upload_path)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.property.models.agency_upload_path)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='property.commune')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='property.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, help_text='e.g. Sales, Rentals, Office', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='property.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('exchange', 'For Exchange')], db_index=True, max_length=10)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=15)),
                ('negotiable', models.BooleanField(default=False)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_m2', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('leads_count', models.PositiveIntegerField(default=0)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.agency')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.commune')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='property.propertytype')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.wilaya')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(upload_to=apps.property.models.property_media_upload_path)),
                ('is_cover', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='property.property')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.wilaya'),
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'unique_together': {('property', 'amenity')},
            },
        ),
    ]
