# Generated by Django 5.2.10 on 2026-01-31 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='owner',
            field=models.ForeignKey(help_text='Primary contact/owner of the agency', on_delete=django.db.models.deletion.CASCADE, related_name='owned_agencies', to=settings.AUTH_USER_MODEL),
        ),
    ]
