# Generated by Django 5.2.10 on 2026-02-01 13:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_agency_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertymedia',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='agency',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='agency_cover'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='agency_logo'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='property_image'),
        ),
    ]
