# Generated by Django 5.2.10 on 2026-04-02 23:49

import apps.property.utils
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertymedia_options_alter_agency_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertymedia',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='agency',
            name='footer_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Paste only the Google Maps embed URL (not iframe)', validators=[apps.property.utils.validate_google_maps_embed_url]),
        ),
        migrations.AddField(
            model_name='agency',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero'),
        ),
        migrations.AddField(
            model_name='agency',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agency',
            name='primary_color',
            field=models.CharField(default='#CBA135', max_length=7),
        ),
        migrations.AddField(
            model_name='agency',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
