# Generated by Django 5.2.10 on 2026-04-02 23:54

import apps.property.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_propertymedia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Paste only the Google Maps embed URL (not iframe)', max_length=2000, validators=[apps.property.utils.validate_google_maps_embed_url]),
        ),
    ]
