# Generated by Django 5.2.10 on 2026-04-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_agency_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='accent_color',
            field=models.CharField(blank=True, help_text="Accent color for the agency's branding", max_length=7, null=True),
        ),
    ]
