# Generated by Django 5.2.10 on 2026-04-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_agency_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='navbar_background_color',
            field=models.CharField(blank=True, default='#0B2B3C', max_length=7, null=True),
        ),
    ]
