# Generated by Django 5.2.10 on 2026-04-04 07:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_agency_navbar_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='about_us_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_us'),
        ),
        migrations.AddField(
            model_name='agency',
            name='about_us_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
