# Generated by Django 5.2.10 on 2026-04-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_agency_about_us_image_agency_about_us_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
