# Generated by Django 5.2.10 on 2026-02-02 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tenant display name', max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier for tenant', unique=True)),
                ('domain', models.CharField(db_index=True, help_text='Primary domain (e.g., tenant1.com)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain name', regex='^[a-zA-Z0-9][a-zA-Z0-9-_.]*[a-zA-Z0-9]$')])),
                ('additional_domains', models.JSONField(blank=True, default=list, help_text='Additional domains for this tenant (JSON array)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('schema_name', models.CharField(blank=True, help_text='Database schema name (optional for schema-based tenancy)', max_length=63, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['domain', 'is_active'], name='tenants_domain_15e001_idx')],
            },
        ),
    ]
